ALTER TABLE public.app_settings
ADD COLUMN IF NOT EXISTS landing_content jsonb NOT NULL DEFAULT '{
  "header_login_button": "Ingresar",
  "hero_title": "",
  "hero_subtitle": "",
  "hero_description": "La plataforma todo-en-uno diseñada para abogados modernos. Centralice clientes, expedientes, agenda y escritos en un solo lugar — con la ayuda de un asistente jurídico de inteligencia artificial. Ahorre horas de trabajo administrativo y dedique más tiempo a lo que realmente importa: defender a sus clientes.",
  "hero_cta_primary": "Ingresar a la aplicación",
  "hero_cta_secondary": "Solicitar la aplicación",
  "features_title": "Todo lo que su despacho necesita",
  "feature_1_title": "Gestión de clientes",
  "feature_1_desc": "Toda la información de sus clientes centralizada y accesible.",
  "feature_2_title": "Expedientes digitales",
  "feature_2_desc": "Organice cada caso con escritos, plazos y documentos.",
  "feature_3_title": "Agenda inteligente",
  "feature_3_desc": "No vuelva a perder una audiencia o cita importante.",
  "feature_4_title": "Asistente con IA",
  "feature_4_desc": "Redacte escritos y consulte normativa con apoyo de inteligencia artificial.",
  "why_title": "Por qué los abogados eligen {app_title}",
  "why_paragraph_1": "En la práctica jurídica, cada minuto cuenta y cada documento importa. Perder un plazo, traspapelar un expediente o no encontrar a tiempo la información de un cliente puede tener consecuencias graves.",
  "why_paragraph_2": "{app_title} le ofrece orden, seguridad y eficiencia: sus datos protegidos en la nube, accesibles desde cualquier dispositivo, con búsqueda inmediata por número de cédula y un asistente con IA que le ayuda a redactar y consultar más rápido.",
  "contact_title": "Solicite acceso a la aplicación",
  "contact_subtitle": "Déjenos sus datos y nos pondremos en contacto para crearle su cuenta.",
  "contact_first_name_label": "Nombre",
  "contact_last_name_label": "Apellido",
  "contact_email_label": "Email (opcional)",
  "contact_message_label": "Mensaje",
  "contact_message_placeholder": "Cuéntenos sobre su despacho y cómo podemos ayudarle…",
  "contact_submit_label": "Enviar solicitud",
  "contact_success_message": "Mensaje enviado. Nos pondremos en contacto pronto.",
  "footer_text": "© {year} {app_title} — {app_subtitle}"
}'::jsonb;